# Generated by Django 5.2.6 on 2025-09-13 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=128, unique=True)),
                ('block_id', models.CharField(max_length=128)),
                ('sender', models.CharField(max_length=128)),
                ('receiver', models.CharField(max_length=128)),
                ('payload_hash', models.CharField(max_length=128)),
                ('timestamp', models.DateTimeField()),
                ('signature', models.TextField()),
                ('lamport_clock', models.IntegerField(default=0)),
                ('vector_clock', models.JSONField(default=dict)),
                ('is_synced', models.BooleanField(default=False)),
            ],
        ),
    ]
