# Generated by Django 5.2.6 on 2025-09-14 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_commandcenter_device_modechangelog_masterledger_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommandCenter',
        ),
        migrations.RemoveField(
            model_name='masterledger',
            name='from_device',
        ),
        migrations.RemoveField(
            model_name='masterledger',
            name='to_device',
        ),
        migrations.RemoveField(
            model_name='localledger',
            name='device',
        ),
        migrations.RemoveField(
            model_name='resyncsession',
            name='device',
        ),
        migrations.AlterUniqueTogether(
            name='localledger',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='ModeChangeLog',
        ),
        migrations.DeleteModel(
            name='MasterLedger',
        ),
        migrations.DeleteModel(
            name='LocalLedger',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='ResyncSession',
        ),
    ]
