# Generated by Django 5.2.6 on 2025-09-13 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalLedgerBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.CharField(max_length=128, unique=True)),
                ('prev_hash', models.CharField(max_length=128)),
                ('payload_hash', models.CharField(max_length=128)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('signature', models.TextField()),
                ('lamport_clock', models.IntegerField(default=0)),
                ('vector_clock', models.JSONField(default=dict)),
                ('is_synced', models.BooleanField(default=False)),
                ('sync_attempts', models.IntegerField(default=0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.device')),
            ],
        ),
    ]
